config/routes.rb
Rails.application.routes.draw do
  resources :vitamins
  get 'pages/contact'

devise_for :users
as :user do
  get "signin" => 'devise/sessions#new'
  delete "signout" => 'devise/sessions#destroy'
  get "signup" => 'devise/registrations#new'
end
get 'pages/about'
get 'pages/contact'
resources :veggies
root to: "veggies#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :veggies
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable
  has_many :vitamins
end

app/models/veggy.rb
class Veggy < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/vitamin.rb
class Vitamin < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
  
end

app/controllers/veggies_controller.rb
class VeggiesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @veggies = Veggy.all
  end

  def show
    @veggy = Veggy.find(params[:id])
  end

  def new
    @veggy = Veggy.new
  end

  def create
    @veggy = current_user.veggies.new(veggy_params)
    if @veggy.save
      redirect_to veggies_path, notice: 'Veggy was successfully created.'
    else
      render :new
    end
  end

  def edit
      @veggy = Veggy.find(params[:id])
    end

  def update
    @veggy = Veggy.find(params[:id])
    if @veggy.update(veggy_params)
      redirect_to veggies_path
    else
      render :edit
    end
  end

  def destroy
    @veggy = Veggy.find(params[:id])
    @veggy.destroy
    redirect_to veggies_url
  end

  private

  def veggy_params
    params.require(:veggy).permit(:name, :image)
  end

end

app/controllers/vitamins_controller.rb
class VitaminsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  # GET /vitamins
  def index
    @vitamins = Vitamin.all
  end

  # GET /vitamins/1
  def show
    @vitamin = Vitamin.find(params[:id])
  end

  # GET /vitamins/new
  def new
    @vitamin = current_user.vitamins.new
  end

  # GET /vitamins/1/edit
  def edit
    @vitamin = current_user.vitamins.find(params[:id])
  end

  # POST /vitamins
  def create
    @vitamin = current_user.vitamins.new(vitamin_params)
    if @vitamin.save
      redirect_to @vitamin, notice: 'Vitamin was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /vitamins/1
  def update
    @vitamin = current_user.vitamins.find(params[:id])
    if @vitamin.update(vitamin_params)
      redirect_to @vitamin, notice: 'Vitamin was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /vitamins/1
  def destroy
    @vitamin = current_user.vitamins.find(params[:id])
    @vitamin.destroy
      redirect_to vitamins_url, notice: 'Vitamin was successfully destroyed.'
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def vitamin_params
      params.require(:vitamin).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/veggies_helper.rb
module VeggiesHelper
end

app/helpers/vitamins_helper.rb
module VitaminsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Veggies</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <ul class="nav navbar-nav">
          <li class="nav-item"><%= link_to "Home", veggies_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "About", pages_about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contact", pages_contact_path, class: "nav-link" %></li>
          <% if user_signed_in? %>
            <li class="nav-item pull-md-right"><%= link_to "Log out",
            signout_path, method: :delete, class: "nav-link" %></li>
          <% else %>
            <li class="nav-item pull-md-right"><%= link_to "Sign up",
             signup_path, class: "btn btn-success" %></li>
             <li class="nav-item pull-md-right"><%= link_to "Sign in",
              signin_path, class: "nav-link" %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container">
      <!-- Flash Messages -->
      <% flash.each do |name, message| %>
        <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
      <% end %>

      <!-- Page Content -->
        <%= yield %>

      <!-- Footer -->
      <footer class="small text-muted">
        <div class="container">
          <hr>
            <center>
              <p>Maartje O'Connor</p>
            </center>
        </div>
      </footer>

  </body>
  </html>

app/views/pages/about.html.erb
<div class="jumbotron">
<div class="container">
<h1>About</h1>
<p>This is one of my projects, I am currently learning how to code! :)</p>
</div>
</div>

app/views/pages/contact.html.erb
<div class="jumbotron">
  <div class="container">
<h1>Contact</h1>
<p>Have any questions? Send me an <a href="mailto:m.j.oconnor88@gmail.com" class="text-success">e-mail</a></p>
  </div>
</div>

app/views/veggies/edit.html.erb
<%= form_for @veggy do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.submit "Update Veggy" %>
  </div>
<% end %>

app/views/veggies/index.html.erb
<div class="jumbotron jumbotron-home"></div>
<h1> Veggies </h1>
<ul>
  <% @veggies.each do |veggy| %>
    <li>
      <%= link_to veggy.name, veggy, class: "text-success" %>
    </li>
  <% end %>
</ul>

<% if user_signed_in? %>
  <p class="nav-item"><%= link_to "New Veggy", new_veggy_path, class: "btn btn-success" %></p>
<% end %>

app/views/veggies/new.html.erb
<%= form_for @veggy, url: veggies_path, html: { multipart: true} do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div>
    <%= f.submit "Add Veggy" %>
  </div>
<% end %>

app/views/veggies/show.html.erb
<h1 class="nav-item"><%= @veggy.name %></h1>
<%= image_tag @veggy.image, class: "img_fluid" %>
<% if @veggy.user == current_user %>
  <%= link_to "Edit", edit_veggy_path, class: "btn btn-warning" %>
  <%= link_to "Destroy", @veggy, method: :delete, class: "btn btn-danger" %>
<% end %>
<p><%= link_to "Back to Veggies", veggies_path, class: "text-success" %></p>

app/views/vitamins/_form.html.erb
<%= form_with(model: vitamin, local: true) do |form| %>
  <% if vitamin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vitamin.errors.count, "error") %> prohibited this vitamin from being saved:</h2>

      <ul>
      <% vitamin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, id: :vitamin_content, class: "form-control" %>
  </div>

    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/vitamins/edit.html.erb
<div class= "container">
  <h1>Editing Vitamin</h1>
  
  <%= render 'form', vitamin: @vitamin %>
  <%= link_to 'Back', vitamins_path, class: "text-success" %>
</div>

app/views/vitamins/index.html.erb
<div class="container">

  <h1>Vitamins</h1>

  <table class="table">
    <thead>
      <tr>
        <th>User</th>
        <th>Content</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @vitamins.each do |vitamin| %>
        <tr>
          <td><%= vitamin.user.email %></td>
          <td><%= vitamin.content %></td>
          <td><%= link_to 'Show', vitamin, class: "text-success" %></td>
          <% if vitamin.user == current_user %>
            <td><%= link_to 'Edit', edit_vitamin_path(vitamin), class: "text-success" %></td>
            <td><%= link_to 'Destroy', vitamin, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-success" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
<% if user_signed_in? %>
  <%= link_to 'New Vitamin', new_vitamin_path, class: "text-success" %>
<% end %>

</div>

app/views/vitamins/new.html.erb
<div class="container">
  <h1>New Vitamin</h1>

  <%= render 'form', vitamin: @vitamin %>

  <%= link_to 'Back', vitamins_path, class: "text-success" %>
</div>

app/views/vitamins/show.html.erb
<div class="container">
  <p>
    <strong>User:</strong>
    <%= @vitamin.user.email %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= @vitamin.content %>
  </p>
  <% if @vitamin.user == current_user %>
    <%= link_to 'Edit', edit_vitamin_path(@vitamin), class: "text-warning" %>
  <% end %>
  <%= link_to 'Back', vitamins_path, class: "text-success" %>
</div>